### ISSUE TITLE
Data loader uses old route params, when navigation changes to to fast.

### ISSUE THREAD

**Issue by minht11** [posva/unplugin-vue-router#200]
Data loader uses old route params, when navigation changes to to fast.
 
### Reproduction

1. Go to example https://stackblitz.com/edit/vitejs-vite-xntgcq
2. Click on link "Test 2" few times, then quickly click on link "Test 1"
3. Observe that `params` from current route, and data loader mismatch.

https://github.com/posva/unplugin-vue-router/assets/8914032/d1f6daad-8bf9-425a-85bc-a2cd24906a49

**Comment by posva** [comment]
This might be related to #201. I think it's a mix of the current cached behavior and not properly discarding old fetching. I think adding different stages to the data, e.g. waiting for all of the loaders to be resolved before applying will help for this and #201

**Comment by minht11** [comment]
I am trying to patch this locally for myself and it seems, shouldFetchAgain entry  can resursively point to itself.
<img width="636" alt="image" src="https://github.com/posva/unplugin-vue-router/assets/8914032/069cd2e8-8332-4523-9e99-b3b86afff4ec">

I am not sure if that is intended, but the quick fix could be to change this code
https://github.com/posva/unplugin-vue-router/blob/5d9f1086cbe884e8a5e065a0de92665ff6c87b76/src/data-fetching/defineLoader.ts#L301-L315

to check if entry and child entry are not the same

```ts
Array.from(entry.children).some((childEntry) => 
      entry !== childEntry && shouldFetchAgain(childEntry, route) 
     ) 
```

**Comment by posva** [comment]
@minht11 Some heads-up: this and other bugs are fixed but the next release will likely be a major that replaces the current implementation of defineLoader. I haven't written the changelog yet and I do hope to add deprecations in the meantime but the new fixed version does not have a cache (yet) and things like `invalidate`, `pendingLoad`, and `cacheTime` do not exist anymore. Ideally, I will create another define loader for cache that uses a light lru cache but I think the priority should be having a loader with no cache (since most of GET cache should be handled at server level anyway) and move from there to support other patterns and update https://github.com/vuejs/rfcs/discussions/460
