### ISSUE TITLE
Get all routes as enum

### ISSUE THREAD

**Issue by eddie-englund** [posva/unplugin-vue-router#209]
It would be nice to be able to get all the parsed routes as an enum so that I can get the name of each view outside of components.

Let me know if this is a feature already (I don't think it is).

Cheers

**Comment by posva** [comment]
They do exist: https://github.com/posva/unplugin-vue-router#routelocationresolved. You can even see the types in the generated d.ts file: https://github.com/posva/unplugin-vue-router/blob/main/playground/typed-router.d.ts. Namely [RouteNameMap](https://github.com/posva/unplugin-vue-router/blob/main/playground/typed-router.d.ts#L41) and [RouteLocationRaw](https://github.com/posva/unplugin-vue-router/blob/main/playground/typed-router.d.ts#L110)

**Comment by eddie-englund** [comment]
Hi,

@posva but these only refer to the types? I'm looking for an actual enum such as Routes.myRoute.path

where myRoute would be something like the name of the route but inherited as a key.

**Comment by posva** [comment]
You can access the routes with router.getRoutes()

**Comment by puyt** [comment]
This is also preventing me from using this package, it looks very promising, but we heavily really on programmatic navigation using Enum values rather than paths.

`router.getRoutes()` wouldn't solve this either and the provided examples for `RouteLocationResolved` are also confusing, especially the last one which seems to be recommended:

```
// these are all valid
let userWithId: RouteLocationNormalizedLoaded<'/users/[id]'> = useRoute()
userWithId = useRoute<'/users/[id]'>()
// 👇 this one is the easiest to write because it autocomplete
userWithId = useRoute('/users/[id]')
```

I would expect that the following piece of code returns the matching route as provided in the parameters: `useRoute('/users/[id]')`, instead it just returns the current route but with different type.

**Comment by posva** [comment]
I'm not sure of what you are trying to do but it looks like it's

```ts
const router = useRouter()
router.resolve({ name: '...' })
```

> we heavily really on programmatic navigation using Enum values rather than paths.

That shouldn't be an issue as long as your enum has the proper values. I personally find it much more convenient to **not** use an enum and directly use strings because of the auto complete and the fact that they are generated and guaranteed unique. You could still create a Vite plugin that generates the enum from the routes. It could be in one of the hooks like `beforeWriteFiles()`.

**Comment by puyt** [comment]
Currently, our setup looks more like this:

We have multiple routes files, e.g.
```javascript
// user.routes.js
export const Route = {
    USER_OVERVIEW: 'user_overview',
    USER_DETAIL: 'user_detail',
};

const routes = [
    {
        path: '/users',
        name: Route.USER_OVERVIEW,
        component: () => import('..'),
        props: true,
        children: [
            {
                path: ':userId',
                name: Route.USER_DETAIL,
                component: () => import('..'),
            },
        ],
    },
];
```

We then use the "Enum" in order to change the router in certain places:
```js
const router = useRouter();
router.push({ name: Route.USER_OVERVIEW });
```
Or we use it to compare the current route with the "Enum" in order to do stuff or as computed properties.
```js
const currentRoute = useRoute();

if (currentRoute.name === Route.USER_OVERVIEW) {
  ...
}
```

You're right that the router push should not be big of an issue because of the autocomplete, except for the fact that I'll have to update multiple places if we would decide to change the route. Also, I don't see an easy solution for the 2nd usage, the compare of the current route.

**Comment by posva** [comment]
the compare is the same, you get autocomplete too. My recommendation is to not write route names like this and let the plugin generate them based on the folder structure. You can still use your own names from the enum with

```ts
definePage({ name: Route.USER_OVERVIEW })
```

Or create your custom function getRouteName but I really recommend you to migrate to the default behavior in the long term 🙂
