### ISSUE TITLE
in latest playground vue-router/auto only have type 'export interface RouteNamedMap {} '

### ISSUE THREAD

**Issue by Miofly** [posva/unplugin-vue-router#345]
![image](https://github.com/posva/unplugin-vue-router/assets/42859910/01253738-7877-40f5-b5ff-c846ae7c6605)

**Comment by ultimateshadsform** [comment]
> yes, it's meant to be extended. Please don't open non-conforming issues, thanks.

Then what's the point of even using this plugin at all if it doesn't even generate the types???

Mine is also empty and is getting errors.
![image](https://github.com/posva/unplugin-vue-router/assets/151234273/50fcc4db-c875-4d18-bd60-1c21931920d2)

![image](https://github.com/posva/unplugin-vue-router/assets/151234273/93138c39-b8b5-4bf2-a50d-9bfd09d59f57)

**Comment by posva** [comment]
I should have locked the issue…
You probably have something else missing or misconfigured. Open a discussion or ask on discord for help. Commenting like this on an issue is not helpful for you since you’re not providing information to get help but rather to complain. It’s not helpful for me either because I cannot detect a possible bug either without enough information to reproduce
