### ISSUE TITLE
Support definePage() with import other js

### ISSUE THREAD

**Issue by wsi18n** [posva/unplugin-vue-router#487]
## current
in xxxx.vue
``` js
<script lang="ts" setup>
import router from '@/router'

definePage({
  meta: {
    title: () => `project: ${router.currentRoute?.query.code}）`,
  },
  props: route => route.query,
})

```
but parsed to xxxx.vue?definePage&vue like this:
``` js
export default {
    meta: {
        title: ()=>`project: ${router.currentRoute?.query.code}）`,
    },
    props: route=>route.query,
}
```
throw error ``` Uncaught (in promise) ReferenceError: router is not defined``` 

## expect
 plan A：parsed to  xxxx.vue?definePage&vue with useful import by AST analysis
 plan B：`<route />` support lang="ts":
``` vue
<route lang="ts/js">
import router from '@/router'
export default {
    meta: {
        title: ()=>`project: ${router.currentRoute?.query.code}）`,
    },
    props: route=>route.query,
}
</route>
```

**Comment by posva** [comment]
Imported variables [already works](https://github.com/posva/unplugin-vue-router/commit/a113a2d765aac884ca5a11adb4cba644d1515cc1), it seems like you have an outdated version from what I tested locally.

That being said, you can't use the router instance because it creates a cyclic import. If you need the router, pass it as an argument:

```ts
definePage({
  meta: {
    title: (router) => `project: ${router.currentRoute?.query.code}）`,
  },
  props: route => route.query,
})
```
