### ISSUE TITLE
✨ Align generated routes with Nuxt

### ISSUE THREAD

**Issue by jd-solanki** [posva/unplugin-vue-router#78]
Hi,

I was using [`vite-plugin-pages`](https://github.com/hannoeru/vite-plugin-pages) and want to give `unplugin-vue-router` a try but unfortunately switching to `unplugin-vue-router` breaks my app as it generates nested routes different than nuxt & vite-plugin-pages.

With nuxt & vite-plugin-pages we get route name as `parent-child` whereas with unplugin-vue-router we get `/parent/child`.

Reference: https://v3.nuxtjs.org/guide/directory-structure/pages#nested-routes

Thanks :)

**Comment by posva** [comment]
You can already customize this with `getRouteName()` https://github.com/posva/unplugin-vue-router#configuration.

The nesting in routes is intentional as we added the feature in Vue Router to improve router declaration.

If there is anything specific you tried (in terms of file structure) that didn't work while it worked in Nuxt, let me know because the idea is to have something that is able to work with the same folder structure.
