### ISSUE TITLE
Component's name should be automatically generated by `route.name` for `keep-alive`

### ISSUE THREAD

**Issue by zhiyuanzmj** [posva/unplugin-vue-router#95]
### Description
It was inspired by https://github.com/vuejs/core/issues/4993

I want to create a new plugin to implement it for this I need to export the 'getRouteMap' api.
Or implement it directly in the current plugin. like this: https://github.com/hannoeru/vite-plugin-pages/pull/323 .
What do you think?

**Comment by posva** [comment]
Names are already generated. You can also override them in multiple ways shown in the readme
I don’t understand

**Comment by zhiyuanzmj** [comment]
In my application, I must manual specify component's name use `unplugin-vue-macros`  :
``` ts
<script setup>
defineOptions({
  name: '/blogs'
})
</script>
```
but, when I update the file structure, I also need to multiple update component's name.
so I want create a plugin to  automatically generate component's name.

**Comment by posva** [comment]
aah, usually vue already generates the name of the component based on the filename, if you want to do something different, I believe this should be declared locally, in each component.

If you want, you can create your own vite plugin to automatically generate this part for you but keep in mind this problem is simple for common cases but gets more complicated with others (already declared `export default ()`, etc) and the complexity added in the end is probably not worth it given how easy it is to add a name to a component

**Comment by qasdcl** [comment]
so how use keep-alive includes field without define component name?
in this case we need a component name

**Comment by qasdcl** [comment]
defineOptions({
  name: 'home',
})
definePage({
  name: 'home',})
  

<keep-alive :include="['home']">
  <component :is="Component" :key="route.name" />
</keep-alive>

I have to do this. otherwise router cache is no work.
